### ISSUE TITLE
<style> example breaks editor

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#1013]
[The example for `<style>`](https://interactive-examples.mdn.mozilla.net/pages/tabbed/style.html) breaks the editor UI when the CSS is edited:

![html-style-bug](https://user-images.githubusercontent.com/432915/42291670-1d4870b6-7f82-11e8-9e22-6042bf69131c.gif)

I have no idea why. It's possible that `<style>` won't be suitable for an interactive example.

**Comment by stephanmax** [comment]
I think what blows up here is this code inside the `render` function in [editor.js](https://github.com/mdn/interactive-examples/blob/master/js/editor.js):

```javascript
var styleElements = shadow.querySelectorAll('style'); // A

for (var styleElement in styleElements) {
    if (styleElements.hasOwnProperty(styleElement)) {
        shadow.removeChild(styleElements[styleElement]); // B
    }
}
```

All `style` elements are selected (`A`), including the one coming from inside the HTML editor. Since that one is not a direct child of the shadow root, calling `removeChild` (`B`) on it throws an error. The `render` method exits and we are left with only the `div` element but no more `style` elements.

I think deleting the `div` first (and the `style` element from the HTML editor with it), before we query the DOM, is the cheapest solution here. PR is coming right up.
