### ISSUE TITLE
JS editor: if the output box overflows, the entire iframe gets scrollbars

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#102]
-> http://imgur.com/a/j7oyY

**Comment by schalkneethling** [comment]
So, we can force the strings to wrap but, because we are in this fixed height scenario, the output it most likely going to spill out of the container.

One possible option is to expand the default height of the output container, force the output to wrap, and then introduce a vertical scrollbar should the output overflow.

For example:

Default with minimal output

![screen shot 2017-07-10 at 13 27 30](https://user-images.githubusercontent.com/10350960/28016324-307f356c-6574-11e7-8d1c-d81858e77272.png)

With output overflowing the output container

![screen shot 2017-07-10 at 13 28 21](https://user-images.githubusercontent.com/10350960/28016337-39bbc2c6-6574-11e7-8214-61b1bae2ffc5.png)

Thoughts @stephaniehobson @wbamberg

**Comment by stephaniehobson** [comment]
I think the slightly expanded output container is a good solution. When there is only one line of output can we vertically centre it?

**Comment by schalkneethling** [comment]
> I think the slightly expanded output container is a good solution. When there is only one line of output can we vertically centre it?

Sounds good.
