### ISSUE TITLE
color-adjust example does not render or work in Chrome 69 or Safari

### ISSUE THREAD

**Issue by joshunger** [mdn/interactive-examples#1033]
1. Open Google Chrome Canary 69
2. Visit https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust

![image](https://user-images.githubusercontent.com/2301847/42637730-2b016ece-85a9-11e8-869d-3921d48f088b.png)

The example works correctly FireFox Nightly.
![image](https://user-images.githubusercontent.com/2301847/42638122-1adfeea2-85aa-11e8-8c6f-d950803776f1.png)

**Comment by wbamberg** [comment]
Thanks for filing!

It's because this property is prefixed in Chrome, and we don't auto-prefix (yet). We have the beginning of a plan to deal with cases like this better (https://github.com/mdn/interactive-examples/issues/532#issuecomment-404235636). In the meantime, though, this is a bad experience for a lot of our users so I have removed the example from the page.
