### ISSUE TITLE
CSS position example doesn't work in Safari

### ISSUE THREAD

**Issue by guillaumebreux** [mdn/interactive-examples#1115]
**Related article:** https://developer.mozilla.org/en-US/docs/Web/CSS/position

After looking at this example on safari, you can see that there is no prefix on the sticky property causing the example to fail.

But, even if you set the prefix, it won't work because the element is a `inline-block` element and Safari seems to only apply this position value on a `block` element (see here: http://jsfiddle.net/hg6Lqk7n/8/)

I don't know if the solution is to wait for safari to fix the issue or if you could tweak the exemple a little to make it work or to warn the user that it will fail on safari (v11.1.2) ? 

Anyway, the prefix is still needed and I could find where to make the change to make a PR :(

**Comment by wbamberg** [comment]
Thanks for filing!

> I don't know if the solution is to wait for safari to fix the issue or if you could tweak the exemple a little to make it work or to warn the user that it will fail on safari (v11.1.2) ?

There's some previous chat about how the editor should behave when properties aren't well supported across browsers: https://github.com/mdn/interactive-examples/issues/532. We have a proposal for how to handle this, but it's not a very high priority at the moment just because cross-browser support is in general pretty good. Still it would be great to have a fix for this in the editor.

In this case, though, I think it would be possible for the example to work in Safari, and it would be worth doing. We could add `position: -webkit-sticky;` to the [CSS for the `sticky` option](https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/positioned-layout/position.html#L27-L28), and [make the box `display: block;`](https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/positioned-layout/position.css#L11). We'd also need to adjust the markup, but it seems simple - we could just remove those 2 blue boxes I think, and then adjust the red dotted box so it overlaps with the yellow box.

If you want to file a PR, please do go ahead! Otherwise we can leave this open and perhaps someone will take it before I manage to fix it.

The changes would all be in [position.html](https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/positioned-layout/position.html), plus changes to the positioning of `#example-element-placeholder` in [position.css](https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/positioned-layout/position.css). The [general contributing guide](https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING.md) covers how to make and test changes.

**Comment by schalkneethling** [comment]
@wbamberg Should we close out this issue? The PR that addressed this was also closed as it did not quite work in Safari so, it seems we are ok with that?

**Comment by wbamberg** [comment]
I'd accept a PR that fixes the behavior in Safari, but I don't have the time to dig into why it doesn't work properly.

**Comment by stephanmax** [comment]
@wbamberg, happy to dig into this.

**Comment by wbamberg** [comment]
@stephanmax , that would be awesome! In case it helps, you can find my attempt here: https://github.com/mdn/interactive-examples/pull/1121. It seems like Safari support is tricky and I didn't have the time to dig into why :(
