### ISSUE TITLE
Style changes for CSS Editor

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#143]
Follow Brigades suggestions except for the width of the input area. Here we should use the current split where more space is allotted for the code and less for the output.

Then also, styling for the states will be as follows:

## Active state

Essentially follow the suggestion from Brigade

![68747470733a2f2f643236647a786f616f36693368682e636c6f756466726f6e742e6e65742f6974656d732f31783353303430323038304831673169334a32432f53637265656e25323053686f74253230323031372d30372d3237253230617425323031302e30352e35322e706e673f763d656232343438](https://user-images.githubusercontent.com/10350960/28686300-098c4252-730b-11e7-8ce4-c88cddef0eb0.png)
  
Also change the arrow on the right to blue.

## Inactive state

The inactive state will use the light grey colour used for the border for the left side border as well.
The code will by syntax highlighted but, experiment with setting an opacity of `.8` to slightly fade it out.

## Reset  button

The reset button moves to the bottom and on click, resets all of the examples to their original state.

## Vertical alignment

When the CSS editor switches to a vertical aka stacked layout, everything remains as is except, the arrow on the right hand side is hidden.

**Comment by wbamberg** [comment]
If I understood, we discussed scrapping the rather dark background-color for unselected items (rgb(224, 224, 224) and just using white (or at least the same near-white as is used for the selected item).

So we use the blue border and arrow to indicate that this item is selected, rather than a background color. This sounds quite promising to me, at least to look at.

Then as you say we also discussed using .8 opacity on the unselected items, to further emphasise their unselectedness.

But do we also need a hover state for unselected items, so the user understands that they are selectable?

**Comment by schalkneethling** [comment]
> If I understood, we discussed scrapping the rather dark background-color for unselected items (rgb(224, 224, 224) and just using white.

> So we use the blue border and arrow to indicate that this item is selected, rather than a background color. This sounds quite promising to me. At least it seems like it's worth a try :).

> Then as you say we also discussed using .8 opacity on the unselected items, to further emphasise their unselectedness.

Exactly

>But do we also need a hover state for unselected items, so the user understands that they are selectable?

Yeah, I do not believe we discussed this specifically. So before we had the darkish grey, on hover it would be a lighter grey, and then on click it would go white. I am thinking perhaps a lighter blue border, and when you click, the darker blue as defined in the colour palette.

**Comment by wbamberg** [comment]
I think this looks so nice.

It's worth looking back to see how far it's come: https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/transform:v2 :)

I'm worried that the opacity (.6) is too extreme for the non-selected options. We want this to work well as a replacement for the existing "syntax examples", for people who don't want to use the interactive feature, but just want to read the options. And I'm worried that .6 hurts readability.

The problem with something like .8 instead is that the hover state is much less obvious, so it's less clear that this is a list of selectable options. I did try .8 and a border-width of 2px (since the gray->blue border color change is also a hover state cue). Do you think that works? @schalkneethling , @stephaniehobson ? I'm happy to defer to your judgement on this.

**Comment by wbamberg** [comment]
Sorry that last paragraph makes no sense - opacity does nothing for the hover state.

But .8 (rather than .6) does make the selected item stand out less, and a border-width of 2px might help with that problem, while keeping the unselected items readable.

**Comment by atopal** [comment]
I don't have anything of substance to add here, just wanted to echo what Will said, love where this is going and how we got here: through quick prototyping and many rounds of refinements based on user testing. This is a great model to follow for major new site features in the future. Great job everyone 👍

**Comment by stephaniehobson** [comment]
We've come [even further than that](https://mdn.github.io/css-examples/editable-samples/pages/font/index-old.html)!
