### ISSUE TITLE
Notification API example doesn't work in Chromium in cross-origin iframe.

### ISSUE THREAD

**Issue by hasparus** [mdn/interactive-examples#1457]
## 🐛 Bug Description

I've given the permission, but the notification doesn't appear. I've found following deprecation message in the console.

> Example?revision=1583240:39 [Deprecation] Permission for the Notification API may no longer be requested from a cross-origin iframe. You should consider requesting permission from a top-level frame or opening a new window instead. See https://www.chromestatus.com/feature/6451284559265792 for more details.

CodePen and JSFiddle have the same problem. I suppose linking to the demo and describing why would be an okayish workaround.

## 📃 Steps to reproduce

- visit https://developer.mozilla.org/en-US/docs/Web/API/notification
- click <kbd>Notify me</kbd> button

---

TBH I'm not sure if this is the right repo to file this issue. It's connected to the interactive example, but the change should probably be made in the repository with the docs content.

**Comment by wbamberg** [comment]
@hasparus , thanks for the bug report! This is actually an issue with a *live sample* not an *interactive example* (yes this is totally confusing) so needs to be fixed in the MDN wiki itself, not in the interactive-examples repo.

I've cross-filed it as https://github.com/mdn/sprints/issues/2243, where it ought to get some attention.
