### ISSUE TITLE
list-style-type with content not working in chrome (Version 78.0.3904.87)

### ISSUE THREAD

**Issue by velusgautam** [mdn/interactive-examples#1466]
<img width="1121" alt="Screenshot 2019-11-03 at 10 35 31" src="https://user-images.githubusercontent.com/8556085/68083281-3f424c80-fe27-11e9-9af4-ffb669db1bff.png">

**Comment by wbamberg** [comment]
I think Chrome doesn't support these values, so I'm not sure what's for the best really. We could omit them, but they are nice to have in the example. Ideally we would have a nice way to indicate that particular values are not supported, but we don't, and I don't expect this to change any time soon.

**Comment by velusgautam** [comment]
Can we add a warning box below to show **some features are not supported in chrome**. But I tested in Chrome Canary and except space-counter rest is working.

**Comment by velusgautam** [comment]
I can add a warning box and create a PR. What do you think @wbamberg

**Comment by wbamberg** [comment]
I'm not very keen on adding notes like this because I think they will tend to get out of date when browser support changes. We have a single place in the page where compat data is consistently presented and where we can expect it it maintained - the compat table powered by data from https://github.com/mdn/browser-compat-data. Having extra places is asking for trouble.

The best thing we could do here is to change the interactive example code so it can intelligently signal (or just hide) unsupported properties or values, but as I said I think this is a tricky thing that we're not likely to work on any time soon. See https://github.com/mdn/interactive-examples/issues/532 for some background on this.

Or, we could modify the example to omit space-counter. space-counter is a lovely example, though. Or, we could modify the example so space-counter isn't the initially selected example.
