### ISSUE TITLE
offset-anchor interactive example not displaying

### ISSUE THREAD

**Issue by tannerdolby** [mdn/interactive-examples#1826]
The `offset-anchor` interactive example on https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor isn't displaying at all, just shows 4 lines of CSS and the example output and options aren't visible. 

The `example-output` container actually has the `hidden` class which gives `display: none`, so if that was intended the interactive example is indeed not visible. I don't think the intended behavior was to have the example not displayed.

<img width="1258" alt="Screen Shot 2021-05-30 at 11 53 57 AM" src="https://user-images.githubusercontent.com/48612525/120116629-e3909000-c13d-11eb-920d-5a1466b666b3.png">

Discussed in this related issue #1643

**Comment by wbamberg** [comment]
I guess you are using Chrome? Contrary to the browser compatibility table, it looks like this isn't supported in Chrome (you can see this because the other example in the page doesn't work either: https://developer.mozilla.org/en-US/docs/Web/CSS/offset-anchor#setting_various_offset-anchor_values ).

When a property isn't supported, the interactive example just shows the static list of values, and hides the output. This is confusing, but we've never prioritised a fix for it: https://github.com/mdn/interactive-examples/issues/532.

Does the example work in Firefox?

**Comment by wbamberg** [comment]
Maybe we should face reality and remove interactive examples for properties that aren't supported in Chrome.

**Comment by tannerdolby** [comment]
Yeah I was using Chrome when I viewed the page. Haven't had a look at the page in Firefox.

> Maybe we should face reality and remove interactive examples for properties that aren't supported in Chrome.

That could be a solution. I'm not sure how many of these "scenarios" exist in the interactive examples, if its a large number of them then I think finding a way to display the content in a "documentation" style fashion for browsers that don't support it would be better than explicitly removing them. 

> When a property isn't supported, the interactive example just shows the static list of values, and hides the output. This is confusing

I agree.

**Comment by NiedziolkaMichal** [comment]
Now information about the lack of support is displayed to the users:
![image](https://user-images.githubusercontent.com/100634371/221268125-712fca8d-2735-45b3-a227-b6ab3e626ed6.png)

There is still a lot of empty space under the box, but I will get rid of it in future updates.
