### ISSUE TITLE
Content: position CSS does not have "fixed" example

### ISSUE THREAD

**Issue by shapkarin** [mdn/interactive-examples#1900]
Hello. As you can see at the page https://developer.mozilla.org/en-US/docs/Web/CSS/position interactive example does not have "fixed" example. I created PR https://github.com/mdn/interactive-examples/pull/1896 to fix that.

### Current version
<img width="1022" alt="Screenshot 2021-09-05 at 07 23 14" src="https://user-images.githubusercontent.com/1463086/132115222-d60bd8ba-7668-4d6f-ae26-ec090d0cc767.png">

### Version from #1896 
<img width="1002" alt="Screenshot 2021-09-05 at 07 26 45" src="https://user-images.githubusercontent.com/1463086/132115261-f5b3ee5d-4739-4e70-8fa8-9ec1f1a10807.png">

I hope that PR #1896 done well and it fits nice to the developer.mozilla.org website page. Please recheck if it looks nice with the iframe.

**Comment by wbamberg** [comment]
Thanks for filing this issue, @shapkarin , but it's intentional that `fixed` is omitted. We have a limited amount of space for CSS interactive examples, often not enough space for all the options. If we add `fixed`, then the set of examples will overflow and we will get a scrollbar, and I don't want that.

Interactive examples don't have to show all the syntax: we have the whole page to go into as much detail as we want.

**Comment by seregadushka** [comment]
> we will get a scrollbar, and I don't want that.
Is that the only reason? Scrolling? Is that why it is necessary to cut off a significant part of knowledge? 
Then I suggest throwing out half of the CSS, because the font is the wrong color. 
Do you think that with position:fixed everything fixed already known? You're wrong. 
https://qna.habr.com/q/1363594 --15 comment screens of what you just cropped. 
The number of these comments is your fault.

**Comment by Maykon153** [comment]
E mesmo 😏

Em qui., 1 de ago. de 2024, 19:53, seregadushka ***@***.***>
escreveu:

**Comment by seregadushka** [comment]
> E mesmo :)

Are you normal? Decided to play Spanish Agatha Christie? And become my personal biographer?
I posted these links myself, I am writing about this topic myself. Or rather , about her absence from Mozilla. 
There are still not enough of your toothy smiles here.

**Comment by Maykon153** [comment]
👏

Em qui., 1 de ago. de 2024, 20:46, seregadushka ***@***.***>
escreveu:

**Comment by seregadushka** [comment]
https://github.com/hamishwillee
https://github.com/queengooborg

You couldn't even answer anything. 
You're both pathetic and cheap bums. Your main goal is to sit on your ass and get paid by Mozilla and do nothing. You even have time for this squabble on the forum, and not to fix your own shortcomings in work.
When a person says "we are deleting some of the knowledge, because scrolling is not beautiful" - he should be fired on the same day as a pest to the interests of Mozilla. You check your balance on the card that you haven't earned more often than you open new CSS properties. 
And others suffer from your idleness.
Yes, that's exactly what the truth sounds like.

**Comment by pransh15** [comment]
Both users have been blocked due to spamming and rude behavior. Thanks for locking the conversation @queengooborg. I'm truly sorry that you had to face rude comments from a spammer. Please know that such behavior is not tolerated here, and we will continue taking steps to make this a safe community. Your positive impact on our team and the community is immense, and we are here to support you.

Thank you for your understanding and continued efforts.

**Comment by queengooborg** [comment]
Thank you, @pransh15!  Some people are just like that, unfortunately, and will be outrageously impolite just because they can -- but hey, all it does for them is damage their own reputation, and provide us with a reason to grab some popcorn, right?  😆

**Comment by pransh15** [comment]
That's true, @queengooborg. Being mean is terrible for everyone. Long-time internet residents know, thank you! 🍿
