### ISSUE TITLE
Implement traffic cop for beta test

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#213]
For the beta testing phase, we will need a waffle flag on the Kuma side to ensure only users that have signed up for beta testing see the editor pages.

**Comment by schalkneethling** [comment]
Comment from @atopal

> If we go with the beta testing flag, we’ll only get a small fraction of the traffic these pages usually > see. My suggestion would be that we use the A/B testing framework for those 6 pages. That would > give us half of the traffic they usually see and easily comparable page load times and engagement > scores. Setting up the A/B test is straightforward and can be done in minutes. It does require a push to production to become active though, but so does anything that relies on the waffle flag.

**Comment by stephaniehobson** [comment]
Sounds like @atopal would rather we use Traffic Cop.

I'd say "an hour" rather than "minutes" for setup. I haven't done this myself and don't see any documentation on it. Will can tell you how to set up the pages for the test, and John can tell you want is necessary. Here's the PR for the static examples experiment: https://github.com/mozilla/kuma/pull/4183 you can maybe use that as a template.

**Comment by schalkneethling** [comment]
@atopal What is the percentage split we want to do for the A/B test? 50/50,  70/30?

**Comment by schalkneethling** [comment]
Seeing we will have very few pages, we probably want to make it rather large to ensure we get enough people seeing it. Thoughts? @stephaniehobson @wbamberg

**Comment by schalkneethling** [comment]
PR: https://github.com/mozilla/kuma/pull/4384
