### ISSUE TITLE
<select> example not working

### ISSUE THREAD

**Issue by nikoandpiko** [mdn/interactive-examples#2171]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### What information was incorrect, unhelpful, or incomplete?

The default image is hamster and changing the animal with the select menu does nothing.

### Do you have anything more you want to share?

Using Chrome Version 102.0.5005.61 (Official Build) (x86_64) on macOs 12.4

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md
* Last commit: https://github.com/mdn/content/commit/23c16d3e3f5229cc673a8a1f58d2b06533e3cebd
* Document last modified: 2022-05-15T03:56:08.000Z

</details>

**Comment by wbamberg** [comment]
It's not the intention that the background should change, but I can totally see that this is confusing. I think back in the day other examples, like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option,  also had a background and we removed them, for the same reason: https://github.com/mdn/interactive-examples/pull/800#issuecomment-399287984.

Perhaps we should do that same thing here?

Alternatively we could make it change the background when a new item is selected, but I wouldn't want to do that in JS, because we have (IIRC) no way to show the JS in the demo, which would make it mysterious and confusing. I don't know how we could do it in CSS (maybe with `has()` but that'ts not supported yet).

Or we could switch to an image that's not so obviously one of the options.

**Comment by nikoandpiko** [comment]
@wbamberg You might have a better idea of the best approach, but I think the simplest one would be to replace the image with something that isn't limited to one of the options e.g. a wallpaper with animal silhouettes? Not sure where MDN gathers its resources, but that's just an idea.
