### ISSUE TITLE
Create an interactive example for `HWB()`

### ISSUE THREAD

**Issue by francescorn** [mdn/interactive-examples#2737]
### Proposal

Create an interactive example for [HWB()](/en-US/docs/Web/CSS/color_value/hwb).

### Browser support

It is supported by Chrome, Edge, Firefox, Opera, and Safari.

### Tasks

Create an interactive example for HWB in [Values_and_units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units). 

### Dependencies

Merge pr (with any edits): https://github.com/mdn/content/pull/32100.

### Additional information

Supports the information added in https://github.com/mdn/content/pull/32100

### Are you willing to support this work?

Yes

**Comment by dipikabh** [comment]
Hi @francescorn, the [hwb()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb) page already contains an interactive example (the Try it section). Did you have something else in mind?

We have a separate repository for [interactive examples](https://github.com/mdn/interactive-examples/tree/main) and the guidelines for creating these example types are documented in our [contribution guides](https://github.com/mdn/interactive-examples/tree/main/contributing).

**Comment by francescorn** [comment]
I am wondering if I can add a new interactive example to [Values_and_units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) @dipikabh.

**Comment by dipikabh** [comment]
I've moved this issue to our `interactive-examples` repository, @francescorn.

The page you're referring to, [Values and units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units), belongs in our `Learn` area. We don't add interactive examples there. (The "Values and units" page covers more than just the `<color>` data type.)

We add interactive examples to our reference pages (like the [hwb()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb) page) because they are more specific about a particular feature/property/function.

I am closing this issue for now. Please feel free to reopen if you have more ideas or suggestions for improving the docs.

**Comment by francescorn** [comment]
Okay, thank you @dipikabh. I will post in `interactive-examples` about the interactive-examples.
