### ISSUE TITLE
Infinite loops in code lock page

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#287]
If you create an infinite loop in the interactive editor ie: 
```
var x = 0;
while (x >= 0) {
  x++;
}
```
... the web page locks up, forcing the user to close the page.

Note this does not happen with jsbin (for example).

**Comment by schalkneethling** [comment]
Yup, we are aware of that one. You could also do:

```
for (;;) {
    console.log('We are going down!');
}
```

We thought about handling those situations but, in the end it would have turned out to be way to much that the value. For example, you can do that with jsFiddle as well.

Codepen does handle that[1], and that is basically what I looked at, as they are using CodeMirror as well but, it could potentially add a big dependency, unless we spin that portion of to a separate Nodejs process.

[1] https://github.com/CodePen/InfiniteLoopBuster

**Comment by wbamberg** [comment]
For reference, here's the original bug: https://github.com/mdn/interactive-examples/issues/50. We might want to revisit, but it's not a priority at the moment.
