### ISSUE TITLE
transform-origin example is broken

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#2875]
The examples in the interactive example at https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin are supposed to rotate, but they don't any more. I don't know which other interactive examples might also be broken in this way.

**Comment by lionel-rowe** [comment]
It looks like it's due to the example code blocks being hydrated into codemirror editor components. `transform-origin.js` looks for `.selected code`'s `data-animation` attribute, but `.selected code` no longer exists as it's been overwritten by the editor component.

Possibly attaching the `data-` attributes to the parent `div.example-choice` instead of the child `code` elements would fix it.
