### ISSUE TITLE
image for CSS example "background-size" isn't found

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#344]
In https://interactive-examples.mdn.mozilla.net/pages/css/background-size.html, the image isn't displayed.

In the devtools, the image location is given as:

`background-image:url(../media/examples/hand.jpg);`

which is a 404: if you fix that in the devtools to:

`background-image: url(../../../media/examples/hand.jpg);`

...then it works. The weird thing is, in the code, the path is correct: https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/css/background-size.css.

**Comment by schalkneethling** [comment]
It's there in the prod branch - https://github.com/mdn/interactive-examples/blob/prod/media/examples/hand.jpg :-/

**Comment by schalkneethling** [comment]
Ok so here is the thing. I believe this has to do with how the assets are bundled and pushed to Amazon. If you look at the following example:

https://interactive-examples.mdn.mozilla.net/pages/css/filter.html

It has the image embedded directly in the HTML. You will see that it references it as:
`../../media/examples/firefox-logo.svg`

This is because the HTML file is located here `prod/live-examples/css-examples/filter.html` and the `media` folder is at `prod/media`

Now, for https://interactive-examples.mdn.mozilla.net/pages/css/background-size.html the image is added as a background image here `https://github.com/mdn/interactive-examples/tree/prod/live-examples/css-examples/css/background-size.css` which is nested another level deeper so here, it needs to be referenced as `../../../media/examples/hand.jpg`

This is certainly an inconsistency that is not desired and I will need to file an issue for John, Josh, Dave to have a look but, that is going to take a while with the holidays so, for now, perhaps we should use the workaround above.

**Comment by wbamberg** [comment]
But... in the code it *is* referenced as `"../../../media/examples/hand.jpg"`: https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/css/background-size.css.

**Comment by schalkneethling** [comment]
What the what? Then I wonder what is trimming of the `../../` - ¯\_(ツ)_/¯

Back to the drawing board
