### ISSUE TITLE
CSS examples: tabbing through the examples doesn't move the blue border+arrow

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#349]
If I've selected an example in the CSS editor and tab, I should move to the next example. I do (in that the next example is applied), but the blue border and arrow that's used to indicate the current example isn't updated.

**Comment by diablero13** [comment]
I reviewed this issue and notice that bug have another causal relationship. Switching between examples via tab button occurs because of an improperly setuped event listener:

``` javascript
  exampleChoiceList.addEventListener('keyup', function(event) {
        var exampleChoiceParent = event.target.parentElement;

        cssEditorUtils.applyCode(
            exampleChoiceParent.textContent,
            exampleChoiceParent
        );

        if (!localStorage.getItem('firstCSSEditRecorded')) {
            mceAnalytics.trackFirstEdit('css');
        }
  })
```
The handler is called after each keystroke of any key (with focus on the list of examples) and applies the current code snippet. The problem is that this handler is also called when `tab` key is pressed; default behavior of `tab` is to switch between interactive HTML elements, including the `<code />` element that containing code examples. This means that bug is unacceptable/incorrect tabbing functionality between examples. Since acceptable keyboard control functionality is not implemented yet, so by my opinion good solution will be force disable `tab` navigation on `<code />` element.

**Comment by schalkneethling** [comment]
@diablero13 That sounds like a great analysis. You want to grab this one?

**Comment by diablero13** [comment]
Yes. Actually I already fixed it. I'll make PR soon.

**Comment by schalkneethling** [comment]
Awesome, thanks so mcuh

**Comment by schalkneethling** [comment]
Moved to https://github.com/mdn/bob/issues/548
