### ISSUE TITLE
CSS Examples: Handle scenario where one property value is not supported

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#441]
@wbamberg So, PR #440's update to the `break-word` example will currently work in Chrome, Opera, Safari and Edge, but not in Firefox. It is only one out of four examples so, it is not a good idea to disable the interactive editor just because of the one.

This is probably going to come up more and more as Rachel starts digging in so, I reckon we need to find a solution for this. Perhaps, if the user selects a choice that is not supported, we can show a message along the lines of "The currently selected example is not currently supported in your browser"

Perhaps as a temporary(2-3sec) element next to the heading?

Thoughts?

# Acceptance Criteria

Documentation and proposal on handling scenarios where either a single property, or an entire feature is not supported. The proposal should include a visual prototype and how much effort would be involved in readying a prototype for user testing.

**Comment by schalkneethling** [comment]
@wbamberg Also, do you feel we should block merging https://github.com/mdn/interactive-examples/pull/440 until we solve this?

**Comment by wbamberg** [comment]
I think this is tricky. How can we distinguish between a property value having no effect because this browser doesn't support it, and having no effect because it's invalid?

For example, suppose we have logic like this:
* when the user selects an option, try to apply the CSS. If it doesn't apply, display the "not supported" message.

Now suppose the user edits something like `word-break: none;` to be `word-break: banana;`. The editor will display the "bad syntax" yellow cross. If the user then switches to a different choice, then back to `word-break: banana;`, we don't want to display "not supported".

Similarly, if the user edits `word-break: none;` to `word-break: break-word;`. If Firefox, how is the editor to know that it doesn't apply because it is not supported, not because it's bad syntax?

If we can't get around these edge cases, I wonder if it would be OK to just treat "not supported" and "bad syntax" as the same - yellow cross - and just change things so we always check the result (at the moment we don't check if the user just selected the option - we only check if they actually edited the field). And hope that the user will check the compat table when this happens.

**Comment by chrisdavidmills** [comment]
Would it be possible to derive a dictionary of valid values for the property, from the formal syntax stored in the data repo, and then if the property value has no effect check whether it matches a value in that to distinguish whether it is having no effect because its invalid, or because the browser doesn't support it? Or would that be way too hard?

**Comment by schalkneethling** [comment]
Dang, you are right this is trickier than I initially thought. 

> I wonder if it would be OK to just treat "not supported" and "bad syntax" as the same - yellow cross - and just change things so we always check the result

Not sure, I think it may be more confusing as a user will generally(I think) look at the syntax than the compat table. Seeing the syntax is correct, they may think about compat, but I am thinking they are more likely going to think the example does not work correctly :-/

I do not have a good answer right now though ;) I am going to have to think about this some more. Maybe having browser campat data on top will solve this eventually to some degree and your suggestion above could be a stop gap until then?

**Comment by schalkneethling** [comment]
@chrisdavidmills Yeah, I was thinking of something like this myself. BCD came to mind but, not sure whether that is in a state that we can entirely rely on yet. Also do not believe it has a queryable endpoint, but something like that would be very useful.

As I mentioned in my comment above, having compat data on top should go some way to solve this in future. I was even thinking that the display could be "intelligent". So, if the browser you are using is not green, its section will expand by default to show what is not supported.

For example

![sample](https://user-images.githubusercontent.com/10350960/35263497-af1fbca0-0021-11e8-924c-fa14e8f8504d.png)

**Comment by chrisdavidmills** [comment]
All sounds good, but I was thinking that if we just checked the entered syntax against the BNF representation of the syntax in the data repo (e.g. https://github.com/mdn/data/blob/master/css/properties.json#L1673), you wouldn't need the compat data for this specific purpose. If the entered syntax conforms to the BF, then it is a valid value. Then you can look at whether the browser has successfully rendered the example or not, and use those two pieces of information to work out whether to display one of the two possibilities, e.g.

* Invalid syntax entered
* Browser doesn't support this syntax

So, this is all off the top of my head; I have no idea how feasible this actually is ;-)

**Comment by atopal** [comment]
No idea if this is feasible, but we can detect whether the example was edited, right? If it hasn't been edited and the example doesn't work, we'd show the compatibility message, otherwise we don't. Once the user starts editing, we'd not show anything compatibility related anymore. The point is to make the user aware that there might be issues due to compatibility, right? Covering all potential uses cases might be really difficult, but maybe covering 80% is fairly straight forward. Also, might be a good opportunity to user test, to see what's confusing or not to users.

**Comment by wbamberg** [comment]
@schalkneethling , yes that would help.

@atopal , this is doable but as https://github.com/mdn/interactive-examples/issues/441#issuecomment-359624244 says, will fail in some edge cases. It may still be better than nothing.

>  if we just checked the entered syntax against the BNF representation of the syntax in the data repo (e.g. https://github.com/mdn/data/blob/master/css/properties.json#L1673), you wouldn't need the compat data for this specific purpose. 

@chrisdavidmills , this is a promising idea. The tricky bit is checking "the entered syntax against the BNF representation of the syntax in the data repo". For instance, see [the formal syntax for background-image](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image#Formal_syntax). It's not at all trivial to check whether a given value is valid according to that syntax. I wonder whether [CSSTree](https://github.com/csstree/csstree) would help here, by providing a parser for the formal syntax and for the CSS declaration itself.

**Comment by Elchi3** [comment]
>  BCD came to mind but, not sure whether that is in a state that we can entirely rely on yet. Also do not believe it has a queryable endpoint, but something like that would be very useful.

Well, the whole idea of BCD is to be a queryable compat data store. 
```js
const bcd = require('mdn-browser-compat-data');
bcd.css.properties['word-break']['break-word'].__compat.support.firefox.version_added; // false
bcd.css.properties['word-break']['break-word'].__compat.support.chrome.version_added; // true
```

**Comment by wbamberg** [comment]
From our meeting today, it was decided to:

* as a short-term fix, adopt Kadir's suggestion (https://github.com/mdn/interactive-examples/issues/441#issuecomment-359840729). This leaves some inconsistent edge cases but covers the primary cases and is relatively simple.

* keep a bug open for a long-term fix, which would probably require us to parse and validate the CSS properly, probably using a third-party library.

**Comment by wbamberg** [comment]
-> https://github.com/csstree/validator

**Comment by schalkneethling** [comment]
## Acceptance Criteria

Documentation and proposal on handling scenarios where either a single property, or an entire feature is not supported. The proposal should include a visual prototype and how much effort would be involved in readying a prototype for user testing.

**Comment by schalkneethling** [comment]
@wbamberg I was thinking over this some more, what if we use an approach such as in this POC.

https://codepen.io/schalkneethling/pen/GBxoQM

Let me know your thoughts?

**Comment by NiedziolkaMichal** [comment]
Now when a property value is not supported, the choice box is highlighted with a gold outline and an X sign:
![image](https://user-images.githubusercontent.com/100634371/221271524-72102c8a-a188-4fc5-9784-816f86b3378b.png)

Thanks for the suggestion
