### ISSUE TITLE
CSS pseudo-classes/elements

### ISSUE THREAD

**Issue by mfluehr** [mdn/interactive-examples#527]
Is it currently possible to make examples for pseudo-classes/elements? An interactive example would be nice, e.g., for `:nth-child()`.

**Comment by wbamberg** [comment]
It would indeed be nice. It's not currently possible because the implementation applies the selected choice to the example element as one or more CSS declarations - that is, it doesn't add a new rule to the document's styles, which I think is what we would need.

I'm not against extending the editor in this direction if we can do it in a sensible way, but our main focus is on CSS properties (and I'm happy that it's usable for functions and types as well). Supporting examples for other CSS constructs isn't a major priority for us right now. The next big steps for the editor will be making a version we can use for HTML examples, and one we can use for DOM API examples.

So I'd like to keep this issue, but as a "future enhancement" kind of thing.

**Comment by wbamberg** [comment]
I'm tempted to close this, because the amazing work @NiedziolkaMichal has done on using the tabbed editor for pseudo-classes/elements, and adding the extra examples, (see e.g. https://github.com/mdn/interactive-examples/tree/main/live-examples/css-examples/pseudo-class, https://github.com/mdn/interactive-examples/tree/main/live-examples/css-examples/pseudo-element ) has basically addressed it.

It's really nice to see a 4-year old feature request getting done :).

Unless we should keep it open to track the other ones?

**Comment by Rumyra** [comment]
Let's close it @wbamberg as it's more of a discussion anyway, so if we do want to discuss the improvements from @NiedziolkaMichal we can do that in the community repo 👍 

Thanks @mfluehr for opening!
