### ISSUE TITLE
Naming conflicts (e.g., `perspective`)

### ISSUE THREAD

**Issue by mfluehr** [mdn/interactive-examples#544]
I'm wanting to add an example for the `perspective` property, but it has a naming conflict with the already-existing `perspective()` function. What's the best way to handle this sort of thing?

**Comment by wbamberg** [comment]
I was wondering when/if this would happen.

For the JS examples, we scoped them using the name of the "chapter", like [`typedarray-values`](https://interactive-examples.mdn.mozilla.net/pages/js/typedarray-values.html) or [`object-values`](https://interactive-examples.mdn.mozilla.net/pages/js/object-values.html).

For consistency with that, we could use the CSS module name to scope them, and this would mirror [the organization of the files in the repo](https://github.com/mdn/interactive-examples/tree/master/live-examples/css-examples). Of course that wouldn't help with the immediate problem, because `perspective` and `perspective()` are both in the same module. So perhaps we could also prefix (or suffix) functions, so we could have:

`transform-perspective`
and
`transform-perspective-function` (or `transform-function-perspective`)

What do you think? I'd also be interested to hear what @schalkneethling thinks.

**Comment by schalkneethling** [comment]
Agreed, my vote would be for `transform-perspective-function`

**Comment by wbamberg** [comment]
Fixed! https://github.com/mdn/interactive-examples/pull/568
