### ISSUE TITLE
CSS Examples : display:flex

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#593]
Noticed that the entry page[1] for `flex` does not seem to have a general set of examples to add to the page. Is this intentional @wbamberg or, just not done yet?

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/flex

**Comment by wbamberg** [comment]
I'm not sure what a "general set of examples" means". There isn't yet an interactive example for [`flex`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex). I think it's a bit tricky to do, because the effect of it is dependent not just on the value of the flex item it is applied to, but also on the value of the other flex items.

To demonstrate this, the existing example has different values for all the items, for example:

`auto`/`auto`/`auto`
`auto`/`initial`/`initial`
`auto`/`auto`/`none`

It's hard to replicate this with an interactive example.

I put a note in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Qi1MHvx--6QGGFdboi4VaGVnKf0-kqxwOGMvfdAFhs0/edit#gid=883382855) to that effect, and this might have put people off :(.

Having said that, it would be good to have an interactive example, it would just take some careful design, and we might want to keep the existing example as well. It should also be consistent with the examples for the related properties that @rachelandrew has already written, like [`flex-basis`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis).

**Comment by rachelandrew** [comment]
I think we have the same issue with the `grid` and `grid-template` shorthands. It's a bit tricky to work out which few properties we want to choose. Maybe these just demonstrate the idea, that this is a shorthand, and then refer people to the pages for the individual properties.

**Comment by schalkneethling** [comment]
I really like your idea @rachelandrew - Thanks for the feedback both

**Comment by wbamberg** [comment]
Fixed: https://github.com/mdn/interactive-examples/pull/603/
