### ISSUE TITLE
Styles should blend with MDN page styles

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#68]
Looking at https://developer.mozilla.org/en-US/docs/User:schalkneethling:transform

It's quite jarring that the caption "Try editing..." is a different font to the default font for MDN. I think maybe the black on white is a bit too strong in the context of the page design. since the page design is moving, it's hard to know what to do here, but wherever we end up the styling for the editor should work with the page design.

**Comment by schalkneethling** [comment]
I is odd that it does not use Open Sans for the font, will have a look at that. I am wondering, should that heading perhaps utilise Zilla? That way it would just be another section heading and would use the same style as the other headings with the new design.

I can include a very small subset of just what I need in the iFrame if we decide to do this. Thoughts @wbamberg @stephaniehobson

**Comment by stephaniehobson** [comment]
iframes don't pick up the styles of their parent pages, so, no Open Sans for us :/

I think there are a few options:
1) use a sans-serif font
2) remove the explanatory text (it was removed from the original design because no one was reading it in user testing, though probably it is a good thing to A/B test in the long run)

* I don't think using Open Sans or Zilla are good options because the entire font family would have to be downloaded a second time by the client. We can't use the same files that kuma does because they are versioned so we would either be linking to a versioned file that could have the version number change or to a different un-versioned file :/

**Comment by schalkneethling** [comment]
> use a sans-serif font

Indeed. Just noticed the font-family is not being set in the `body` CSS rule. Let me add that. Does not make sense to load the whole font family for this. `sans-serif` will be close enough.

**Comment by schalkneethling** [comment]
Added in https://github.com/mdn/interactive-examples/pull/96

**Comment by schalkneethling** [comment]
Duping in favour of https://github.com/mdn/interactive-examples/issues/103
