### ISSUE TITLE
CSS cursor example doesn't work with cursor: grab

### ISSUE THREAD

**Issue by nfanta** [mdn/interactive-examples#913]
Hi,

I just noticed that the property `cursor: grab;` is not being properly updated on the example element.

I've checked a bit about how the css examples work and noticed that they use the elements `style.cssText` property to set the example css.
The curious thing is that when I test it on my browser (chrome) it doesn't work, but it does in firefox. (maybe if I'm reading MDN I could use Firefox :stuck_out_tongue_closed_eyes:, but that's another discussion)

I did this little fiddle to test it out: https://jsfiddle.net/zy4kyL4o/

I know that maybe this should be posted as a bug for chrome, but a lot of people uses MDN in chrome, and it would be cool if it uses something that's properly supported by all browsers. Just saying.

**Comment by wbamberg** [comment]
Thanks for filing @nfanta !

The issue here I think is that `grab` must be prefixed in Chrome. Try changing the value to 

```
cursor: -webkit-grab;
```

and it works. It's not clear to me what the interactive examples should do in situations like this. I suppose in a perfect world, they would somehow figure out that the value needs to be prefixed in the particular browser they are running in, then auto-prefix the value on the left-hand side, so the user gets the hint. But that sounds quite hard...

In general this sounds like another manifestation of "the CSS examples should handle support issues more clearly", which is covered by https://github.com/mdn/interactive-examples/issues/534 and https://github.com/mdn/interactive-examples/issues/532, and which I do think we need to look into as soon as we get the time.
