### ISSUE TITLE
Consider removing background images

### ISSUE THREAD

**Issue by wbamberg** [mdn/interactive-examples#996]
See https://github.com/mdn/interactive-examples/pull/800#issuecomment-399287984. We should figure out which examples include "irrelevant" background images and whether the examples would work better without them.

## Acceptance criteria

We've decided whether to remove background images, and done so if we decided we wanted to.

**Comment by a2sheppy** [comment]
That's a tricky one. Some things might seem like the background images are unnecessary, but the images in fact make the example a little more real-world.

**Comment by a2sheppy** [comment]
Have we made decisions on this? I know I used background images in a couple of examples but did so to help demonstrate a technology in something vaguely resembling a real-world scenario, because it makes it easier to understand why you'd use the thing in the first place. Generally yeah, these can be simplified further, but I worry that doing so risks making the element appear less useful in these cases.

**Comment by a2sheppy** [comment]
Submitted PRs to remove backgrounds from the following HTML elements:

* datalist
* optgroup
* option

Submitted a PR to replace the background of the following element with a CC0 one:

* header

These include removing the attribution blocks. I looked through all of the elements, and these are the only ones that needed work regarding removal of backgrounds (header technically is part of cc0 but would have had it removed under slightly different decision-making processes; but I decided that having an example header with a background was useful).

I also checked through the CSS examples and found no situations where removing the background seemed to make sense.
